### PR TITLE
Optimization + fix W3C validator errors

### PR DESCRIPTION
**Pull request by sashachabin**
- [x] Optimize graphics
- [x] Fix `<TeamPerson>` validity (wrap figure with span instead div) 
- [x] Fix wrong CSS values
- [x] Load all resources after button click
- [ ] ~~Remove deprecated `scrolling="no"` in iframe~~ not working

### CODE REVIEW

**Comment by sashachabin** [comment]
Open page

**Before**
image


**After**
image

---


<details>
<summary>
Image optimization
</summary>


</details>

**Comment by sashachabin** [comment]
W3C errors/warnings

**Before**
validator w3 org_nu__showsource=yes nocache=0 009011870585554194 (2)

**After**
image

**Comment by sashachabin** [comment]
**Before**
telegram-cloud-photo-size-2-5305434506905372345-y

**After**
telegram-cloud-photo-size-2-5305434506905372343-y

**Comment by a-chabin** [comment]
<details>
<summary>
Image optimization
</summary>


</details>

**Review by gcor — APPROVED** [review]

**Pull request merged**
